# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yjj/Raft_distributes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yjj/Raft_distributes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjj/Raft_distributes/CMakeFiles /home/yjj/Raft_distributes//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjj/Raft_distributes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named node

# Build rule for target.
node: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node
.PHONY : node

# fast build rule for target.
node/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/build
.PHONY : node/fast

#=============================================================================
# Target rules for targets named kv_store

# Build rule for target.
kv_store: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kv_store
.PHONY : kv_store

# fast build rule for target.
kv_store/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/build
.PHONY : kv_store/fast

#=============================================================================
# Target rules for targets named distributed_lock

# Build rule for target.
distributed_lock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distributed_lock
.PHONY : distributed_lock

# fast build rule for target.
distributed_lock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/build
.PHONY : distributed_lock/fast

#=============================================================================
# Target rules for targets named config_center

# Build rule for target.
config_center: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config_center
.PHONY : config_center

# fast build rule for target.
config_center/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/build
.PHONY : config_center/fast

#=============================================================================
# Target rules for targets named test_callback

# Build rule for target.
test_callback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_callback
.PHONY : test_callback

# fast build rule for target.
test_callback/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/build
.PHONY : test_callback/fast

Asio_mrpc/include/mrpc/ZookeeperUtil.o: Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o
.PHONY : Asio_mrpc/include/mrpc/ZookeeperUtil.o

# target to build an object file
Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o
.PHONY : Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.o

Asio_mrpc/include/mrpc/ZookeeperUtil.i: Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i
.PHONY : Asio_mrpc/include/mrpc/ZookeeperUtil.i

# target to preprocess a source file
Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i
.PHONY : Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.i

Asio_mrpc/include/mrpc/ZookeeperUtil.s: Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s
.PHONY : Asio_mrpc/include/mrpc/ZookeeperUtil.s

# target to generate assembly for a file
Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s
.PHONY : Asio_mrpc/include/mrpc/ZookeeperUtil.cpp.s

example/config_center.o: example/config_center.cpp.o
.PHONY : example/config_center.o

# target to build an object file
example/config_center.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/example/config_center.cpp.o
.PHONY : example/config_center.cpp.o

example/config_center.i: example/config_center.cpp.i
.PHONY : example/config_center.i

# target to preprocess a source file
example/config_center.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/example/config_center.cpp.i
.PHONY : example/config_center.cpp.i

example/config_center.s: example/config_center.cpp.s
.PHONY : example/config_center.s

# target to generate assembly for a file
example/config_center.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/example/config_center.cpp.s
.PHONY : example/config_center.cpp.s

example/distributed_lock.o: example/distributed_lock.cpp.o
.PHONY : example/distributed_lock.o

# target to build an object file
example/distributed_lock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/example/distributed_lock.cpp.o
.PHONY : example/distributed_lock.cpp.o

example/distributed_lock.i: example/distributed_lock.cpp.i
.PHONY : example/distributed_lock.i

# target to preprocess a source file
example/distributed_lock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/example/distributed_lock.cpp.i
.PHONY : example/distributed_lock.cpp.i

example/distributed_lock.s: example/distributed_lock.cpp.s
.PHONY : example/distributed_lock.s

# target to generate assembly for a file
example/distributed_lock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/example/distributed_lock.cpp.s
.PHONY : example/distributed_lock.cpp.s

example/kv_store.o: example/kv_store.cpp.o
.PHONY : example/kv_store.o

# target to build an object file
example/kv_store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/example/kv_store.cpp.o
.PHONY : example/kv_store.cpp.o

example/kv_store.i: example/kv_store.cpp.i
.PHONY : example/kv_store.i

# target to preprocess a source file
example/kv_store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/example/kv_store.cpp.i
.PHONY : example/kv_store.cpp.i

example/kv_store.s: example/kv_store.cpp.s
.PHONY : example/kv_store.s

# target to generate assembly for a file
example/kv_store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/example/kv_store.cpp.s
.PHONY : example/kv_store.cpp.s

example/node.o: example/node.cpp.o
.PHONY : example/node.o

# target to build an object file
example/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/example/node.cpp.o
.PHONY : example/node.cpp.o

example/node.i: example/node.cpp.i
.PHONY : example/node.i

# target to preprocess a source file
example/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/example/node.cpp.i
.PHONY : example/node.cpp.i

example/node.s: example/node.cpp.s
.PHONY : example/node.s

# target to generate assembly for a file
example/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/example/node.cpp.s
.PHONY : example/node.cpp.s

example/test_callback.o: example/test_callback.cpp.o
.PHONY : example/test_callback.o

# target to build an object file
example/test_callback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/example/test_callback.cpp.o
.PHONY : example/test_callback.cpp.o

example/test_callback.i: example/test_callback.cpp.i
.PHONY : example/test_callback.i

# target to preprocess a source file
example/test_callback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/example/test_callback.cpp.i
.PHONY : example/test_callback.cpp.i

example/test_callback.s: example/test_callback.cpp.s
.PHONY : example/test_callback.s

# target to generate assembly for a file
example/test_callback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/example/test_callback.cpp.s
.PHONY : example/test_callback.cpp.s

raftnode.o: raftnode.cpp.o
.PHONY : raftnode.o

# target to build an object file
raftnode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/raftnode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/raftnode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/raftnode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/raftnode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/raftnode.cpp.o
.PHONY : raftnode.cpp.o

raftnode.i: raftnode.cpp.i
.PHONY : raftnode.i

# target to preprocess a source file
raftnode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/raftnode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/raftnode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/raftnode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/raftnode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/raftnode.cpp.i
.PHONY : raftnode.cpp.i

raftnode.s: raftnode.cpp.s
.PHONY : raftnode.s

# target to generate assembly for a file
raftnode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/raftnode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv_store.dir/build.make CMakeFiles/kv_store.dir/raftnode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distributed_lock.dir/build.make CMakeFiles/distributed_lock.dir/raftnode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_center.dir/build.make CMakeFiles/config_center.dir/raftnode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_callback.dir/build.make CMakeFiles/test_callback.dir/raftnode.cpp.s
.PHONY : raftnode.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... config_center"
	@echo "... distributed_lock"
	@echo "... kv_store"
	@echo "... node"
	@echo "... test_callback"
	@echo "... Asio_mrpc/include/mrpc/ZookeeperUtil.o"
	@echo "... Asio_mrpc/include/mrpc/ZookeeperUtil.i"
	@echo "... Asio_mrpc/include/mrpc/ZookeeperUtil.s"
	@echo "... example/config_center.o"
	@echo "... example/config_center.i"
	@echo "... example/config_center.s"
	@echo "... example/distributed_lock.o"
	@echo "... example/distributed_lock.i"
	@echo "... example/distributed_lock.s"
	@echo "... example/kv_store.o"
	@echo "... example/kv_store.i"
	@echo "... example/kv_store.s"
	@echo "... example/node.o"
	@echo "... example/node.i"
	@echo "... example/node.s"
	@echo "... example/test_callback.o"
	@echo "... example/test_callback.i"
	@echo "... example/test_callback.s"
	@echo "... raftnode.o"
	@echo "... raftnode.i"
	@echo "... raftnode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

